### ISSUE TITLE
FE Build CSS and inject HTML for card design

### ISSUE THREAD

**Issue by FaithLilley** [FaithLilley/DnDBeyond-Live-Campaign#4]
```[tasklist]
### Task list
- [x] Set-up core global vars
- [ ] Main function to initialise the page
- [ ] Create HTML, CSS & SVGs for the new character cards & inject
```
